apiVersion: apps/v1
kind: Deployment
metadata:
  name: fams-cms-spa
  namespace: fams-cms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fams-cms-spa
  template:
    metadata:
      labels:
        app: fams-cms-spa
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: fams-cms-spa
        image: pgncontainerregistry.azurecr.io/prajeeshgnair67/azurekube:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          
