apiVersion : apps/v1
kind: Deployment
metadata:
  name: prajeeshgnairazurekube 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prajeeshgnairazurekube
  template:
    metadata:
      labels:
        app: prajeeshgnairazurekube 
    spec:
      containers:
        - name: prajeeshgnairazurekube 
          image: pgncontainerregistry.azurecr.io/prajeeshgnairazurekube
          ports:
          - containerPort: 80